src/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from core import settings


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('auth.urls', namespace='auth')),
    path('cv/', include('cv.urls', namespace='cv')),
    path('profile/', include('user.urls', namespace='user')),
]

if settings.DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls")),]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/cv/urls.py
from django.urls import path

from cv.views import (
    CvCreateView,
    CvDeleteView,
    CvEditView,
    CvItemView,
    CvListView,
)


app_name = 'cv'

urlpatterns = [
    path('list/', CvListView.as_view(), name='list'),
    path('create/', CvCreateView.as_view(), name='create'),
    path('edit/<int:cv_pk>/', CvEditView.as_view(), name='edit'),
    path('delete/<int:pk>/', CvDeleteView.as_view(), name='delete'),
    path('show/<int:pk>/', CvItemView.as_view(), name='show'),
]

src/user/urls.py
from django.urls import include, path

from user.views import (
    CourseView,
    CoursesView,
    ProfileView,
    CreateProfileView,
    EditProfileView,

    ContactView,
    EducationView,
    EmploymentView,
    ProjectsView,
)


app_name = 'user'

urlpatterns = [
    path('', ProfileView.as_view(), name='profile'),
    path('create/', CreateProfileView.as_view(), name='create_profile'),
    path('edit/', EditProfileView.as_view(), name='edit_profile'),

    path('contacts/edit/', ContactView.as_view(), name='edit_contacts'),
    path('education/edit/', EducationView.as_view(), name='edit_education'),
    path('employment/edit', EmploymentView.as_view(), name='edit_employment'),
    path('courses/edit/', CoursesView.as_view(), name='edit_courses'),
    path('projects/edit/', ProjectsView.as_view(), name='edit_projects'),

    path('courses/show/<int:course_pk>/', CourseView.as_view(), name='view_course'),

    path('language/', include('language.urls', namespace='language')),
]

src/cv/models.py
from django.db import models
from django.core.validators import (
    MaxValueValidator,
    MinValueValidator,
)
from django.db.models import QuerySet

from user.models import Profile


class CV(models.Model):
    profile = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE,
        related_name='cvs',
        verbose_name='User cv',
    )
    name = models.CharField(
        max_length=100,
        blank=False,
        verbose_name='CV name',
    )
    avatar = models.ImageField(
        upload_to="images/%Y/%m/%d/",
        blank=True,
        null=True,
        verbose_name="Set cv avatar",
    )
    info = models.TextField(
        blank=False,
        null=False,
        verbose_name='Personal information',
    )
    extra_info = models.TextField(
        blank=True,
        null=True,
        verbose_name="Extra information",
    )

    @property
    def soft_skills(self) -> QuerySet:
        return self.skills.filter(type__iexact='soft')
    
    @property
    def hard_skills(self) -> QuerySet:
        return self.skills.filter(type__iexact='hard')

    def __str__(self) -> str:
        return f'{self.profile} cv: {self.name}'

    class Meta:
        constraints = (
            models.UniqueConstraint(fields=('profile', 'name'), name="Unique cv name constraint"),
        )


class Skill(models.Model):
    SKILL_TYPE = (
        ('hard', 'Hard skill'),
        ('soft', 'Soft skill'),
    )
    cv = models.ForeignKey(
        CV,
        on_delete=models.CASCADE,
        related_name='skills',
        verbose_name='Certain skill',
    )
    type = models.CharField(
        max_length=10,
        choices=SKILL_TYPE,
        verbose_name="Type of skill",
    )
    name = models.CharField(
        max_length=255,
        null=False,
        blank=False,
        verbose_name='Skill name',
    )
    level = models.PositiveSmallIntegerField(
        default=1,
        blank=False,
        null=False,
        validators=[MinValueValidator(1), MaxValueValidator(10)],
        verbose_name="Level of possessing skill in grade from 1 to 10",
    )
    description = models.TextField(
        null=True,
        blank=True,
        verbose_name="Skill description",
    )

    def __str__(self):
        return f'{self.cv.profile} {self.type} skill: {self.name} {self.level}/10'
    
    class Meta:
        verbose_name_plural = 'Skills'
        constraints = (
            models.UniqueConstraint(fields=('cv', 'name'), name='Unique skill name'),
        )

src/cv/forms.py
from django import forms

from ckeditor.widgets import CKEditorWidget

from cv.models import (
    CV,
    Skill,
)


class MyImageInput(forms.ClearableFileInput):
    clear_checkbox_label = "Clear"
    initial_text = "Current avatar"
    input_text = "Set cv avatar"
    template_name = 'cv/widgets/image_widget.html'


class CvForm(forms.ModelForm):
    class Meta:
        model = CV
        exclude = [
            'profile',
        ]

        widgets={
            'avatar': MyImageInput,
            'info': CKEditorWidget,
            'extra_info': CKEditorWidget,
        }


SkillsModelFormSet = forms.modelformset_factory(
    Skill,
    can_delete=True,
    extra=0,
    min_num=1,
    validate_min=True,
    exclude=[
        'cv',
    ],
    error_messages={
        'too_few_forms': 'You must specify at least one skill'
    }
)

SkillsInlineFormSet = forms.inlineformset_factory(
    CV,
    Skill,
    can_delete=True,
    extra=1,
    min_num=1,
    validate_min=True,
    exclude=[
        'cv',
    ],
    error_messages={
        'too_few_forms': 'You must specify at least one skill'
    }
)

src/cv/views.py
from django.contrib import messages
from django.core.exceptions import PermissionDenied
from django.db import transaction
from django.db.utils import IntegrityError
from django.shortcuts import (
    get_object_or_404,
    redirect,
    render,
)
from django.urls import reverse_lazy
from django.views import View
from django.views.generic.edit import DeleteView
from django.contrib.auth.mixins import UserPassesTestMixin


from cv.forms import (
    CvForm,
    SkillsInlineFormSet,
    SkillsModelFormSet,
)
from cv.models import (
    CV,
    Skill,
)
from user.mixins import (
    MyLoginRequiredMixin,
    ProfileRequiredMixin,
)


class CvListView(MyLoginRequiredMixin, View):
    def get(self, request):
        profile = request.user.profile
        cvs = profile.with_cvs_stats.values('pk', 'name', 'softskills_count', 'hardskills_count').all()

        return render(request, 'cv/cv_list.html', {'cvs': cvs})


class CvCreateView(ProfileRequiredMixin, View):
    def get(self, request):
        cv_form = CvForm()
        skills_formset = SkillsModelFormSet(queryset=Skill.objects.none())

        context = {
            'cv_form': cv_form,
            'skills_formset': skills_formset,
        }
        return render(request, 'cv/cv_manage.html', context)

    def post(self, request):
        cv_form = CvForm(data=request.POST, files=request.FILES)
        skills_formset = SkillsModelFormSet(data=request.POST)

        if not (cv_form.is_valid() and skills_formset.is_valid()):
            messages.error(request, 'Please, enter the correct data')
            return render(request, 'cv/cv_manage.html', {'cv_form': cv_form, 'skills_formset': skills_formset})
        
        cv = cv_form.save(commit=False)
        cv.profile = request.user.profile

        try:
            with transaction.atomic():
                cv.save()
                skills = self.get_bulk_skills(skills_formset, cv)
                Skill.objects.bulk_create(skills, ignore_conflicts=False)
        
        except IntegrityError as e:
            messages.error(request, f'Failed to save: {e}')
            return render(request, 'cv/cv_manage.html', {'cv_form': cv_form, 'skills_formset': skills_formset})
        
        # TODO: redirect to cv item page
        messages.success(request, 'CV created successfully')
        return redirect('cv:list')
    
    def get_bulk_skills(self, skills_formset: SkillsModelFormSet, cv: CV) -> list[Skill]:
        """Unpack skill objects from formset, applying to each given cv instance"""
        skills = list()

        for skill_form in skills_formset:
            if skill_form.is_valid() and skill_form.cleaned_data != {}:
                skill_obj = skill_form.save(commit=False)
                skill_obj.cv = cv
                skills.append(skill_obj)
        
        return skills


class CvEditView(ProfileRequiredMixin, View):
    def get(self, request, cv_pk):
        if not request.user.profile.is_owner_of_cv(cv_pk):
            raise PermissionDenied

        cv_obj = get_object_or_404(CV.objects.prefetch_related('skills'), pk=cv_pk)

        cv_form = CvForm(instance=cv_obj)
        skills_formset = SkillsInlineFormSet(instance=cv_obj, queryset=cv_obj.skills.all(), prefix="skills_fs")

        context = self.get_context_data(cv_form, skills_formset)
        return render(request, 'cv/cv_manage.html', context)

    def post(self, request, cv_pk):
        if not request.user.profile.is_owner_of_cv(cv_pk):
            raise PermissionDenied
        
        cv_obj = get_object_or_404(CV, pk=cv_pk)
        
        cv_form = CvForm(instance=cv_obj, data=request.POST, files=request.FILES)
        skills_formset = SkillsInlineFormSet(instance=cv_obj, data=request.POST, prefix="skills_fs")

        if not (cv_form.is_valid() and skills_formset.is_valid()):
            messages.error(request, 'Invalid form data')
            context = self.get_context_data(cv_form, skills_formset)
            return render(request, 'cv/cv_manage.html', context)
        
        try:
            with transaction.atomic():
                cv_form.save()
                skills_formset.save()

        except IntegrityError as e:
            messages.error(request, f'Failed to save data: {e}')
            context = self.get_context_data(cv_form, skills_formset)
            return render(request, 'cv/cv_manage.html', context)
        
        # TODO: redirect to cv item page
        messages.success(request, 'CV edited successfully')
        return redirect('cv:list')
        
    
    def get_context_data(self, cv_form, skills_formset, edit=True):
        return {
            'cv_form': cv_form,
            'skills_formset': skills_formset,
            'edit': edit,
        }


class CvDeleteView(ProfileRequiredMixin, UserPassesTestMixin, DeleteView):
    model = CV
    success_url = reverse_lazy('cv:list')
    success_message = 'CV {cv_name} deleted successfully'

    def form_valid(self, request, *args, **kwargs):
        obj = self.get_object()
        message = self.success_message.format(cv_name=obj.name)

        messages.success(self.request, message)
        return super(CvDeleteView, self).delete(request, *args, **kwargs)
    
    def test_func(self):
        profile = self.request.user.profile
        cv = self.get_object()

        return profile.is_owner_of_cv(cv.pk)


class CvItemView(View):
    def get(self, request, pk):
        cv = get_object_or_404(CV.objects.prefetch_related('skills').select_related('profile'), pk=pk)

        return render(request, 'cv/cv_item.html', {'cv': cv, 'profile': cv.profile})
    

src/cv/templates/cv/cv_confirm_delete.html
{% extends "layout/base.html" %}

{% block content %}

<div class="modal modal-dialog-centered" tabindex="-1" style="display: block;">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Deletion you're CV</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p>You really want to delete "{{ object.name }} CV?"</p>
        </div>
        <div class="modal-footer">
          <a href="{% url 'cv:list' %}" type="button" class="btn btn-secondary">Go back</a>
          <form method="post" action="">
            {% csrf_token %}
              <button type="submit" class="btn btn-danger">Delete</button>
          </form>
        </div>
      </div>
    </div>
  </div>


{% endblock content %}

src/cv/templates/cv/cv_item.html
{% extends "layout/base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block style %}
<link rel="stylesheet" href="{% static 'cv/cv_item.css' %}">
{% endblock style %}

{% block scripts-head %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js" integrity="sha512-GsLlZN/3F2ErC5ifS5QtgpiJtWd43JWSuIgh7mbzZ8zBps+dvLusV+eNQATqgA/HdeKFVgA5v3S/cIrLF7QnIg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
{% endblock scripts-head %}


{% block content %}

{% if request.user.is_authenticated and request.user.profile.id == cv.profile.id %}
  {% include "include/_save_pdf_btn.html" %}
{% endif %}

<div class="row align-items-start">
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <i class="bi bi-person-circle"></i>
                {{profile.full_name}}
            </div>
            <div class="card-body">
                <ul class="list-group list-group-flush">
                    {% if cv.avatar %}
                      
                    <li class="list-group-item">
                        <div class="avatar">
                            <img src="{{cv.avatar.url}}" alt="">
                        </div>
                    </li>
                    {% endif %}
                    <li class="list-group-item">
                        <ul class="list-unstyled profile-info">
                            <li>
                                <b>Birth:</b> <span>{{ profile.date_birth|date:"d.m.Y" }}</span>
                            </li>
                            <li>
                                <b>Born:</b> <span>{{ profile.birth_place }}</span>
                            </li>
                            <li>
                                <b>Live:</b> <span>{{ profile.residence_place }}</span>
                            </li>
                        </ul>
                    </li>
                </ul>

            </div>
        </div>

        <div class="card mt-3">
            <div class="card-header" data-bs-toggle="collapse" data-bs-target="#langs">
                <i class="bi bi-translate"></i>
                Languages
            </div>
            <ul class="list-group list-group-flush" id="langs">
                {% for lang in profile.languages.all %}
                <li class="list-group-item hstack">
                    <div class="">{{ lang.name }}</div>
                    <div
                        class="badge bg-warning-subtle border border-warning-subtle text-warning-emphasis rounded-pill ms-auto">
                        {{ lang.level }}</div>
                </li>
                {% endfor %}
            </ul>
        </div>

        <div class="card mt-3">
            <div class="card-header soft">
                <i class="bi bi-emoji-smile"></i>
                Soft skills
            </div>

            <ul class="p-2 mb-0 skills">
                {% for skill in cv.soft_skills.all %}
                <li class="d-flex justify-content-between align-items-center mb-2">
                    <div class="ms-2 me-auto">
                        <div class="fw-bold">{{ skill.name }}</div>
                        <span class="text-secondary">
                            {{ skill.description }}
                        </span>
                    </div>
                    <span class="badge bg-info-subtle border border-info-subtle text-info-emphasis rounded-pill">
                        {{ skill.level }}/10</span>
                </li>
                {% endfor %}
            </ul>

            <div class="card-header">
                <i class="bi bi-cpu"></i>
                Hard skills
            </div>

            <ul class="p-2 mb-0 skills">
                {% for skill in cv.hard_skills.all %}
                <li class="d-flex justify-content-between align-items-center mb-2">
                    <div class="ms-2 me-auto">
                        <div class="fw-bold">{{ skill.name }}</div>
                        <span class="text-secondary">
                            {{ skill.description }}
                        </span>
                    </div>
                    <span class="badge bg-info-subtle border border-info-subtle text-info-emphasis rounded-pill">
                        {{ skill.level }}/10</span>
                </li>
                {% endfor %}
            </ul>
        </div>

        <div class="card mt-3">
            <div data-bs-toggle="collapse" data-bs-target="#contacts" class="card-header">
                <i class="bi bi-person-lines-fill"></i>
                Contacts
            </div>
            <ul class="list-group list-group-flush" id="contacts">
                {% for contact in profile.contacts.all %}
                <li class="list-group-item">
                    {{contact.template}}
                </li>
                {% endfor %}
            </ul>
        </div>

        <div class="card mt-3">
            <div class="card-header">
                <i class="bi bi-search"></i>
                Courses
            </div>
            <ul class="mt-2 mb-2 courses">
                {% for course in profile.courses.all %}
                <li class="mb-1">
                    <a class="icon-link icon-link-hover link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover"
                        href="{% url 'user:view_course' course.pk %}">
                        <i class="bi bi-link-45deg"></i>
                        {{ course.name }}
                    </a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="col-md-8">
        <div class="card">
            <div class="card-header">
                <i class="bi bi-file-person"></i>
                About me:
            </div>
            <div class="card-body">
                {{ cv.info|safe }}
            </div>
        </div>

        <div class="card mt-3">
            <div class="card-header">
                <i class="bi bi-book"></i>
                Education
            </div>
            <table class="table" style="margin-bottom: 0;">
                <tbody>
                    {% for edu in profile.education_set.all %}
                    <tr>
                        <td>
                            <span>{{ edu.degree }}</span><br>
                            <span class="text-secondary">{{edu.institution}}</span>
                        </td>
                        <td>{{ edu.speciality }}</td>
                        <td>
                            {{ edu.date_start|date:"d.m.Y" }} - {% if edu.date_end %}{{ edu.date_end|date:"d.m.Y" }}
                            {%else %}Current{% endif %}
                        </td>
                    </tr>

                    {% endfor %}
            </table>
        </div>

        <div class="card mt-3">
            <div class="card-header">
                <i class="bi bi-building"></i>
                Employment
            </div>
            <div class="list-group list-group-flush">
                {% for emp in profile.employments.all %}

                <div class="list-group-item">
                    <div class="d-flex w-100 justify-content-between">
                        <div>
                            <h6 class="mb-1">{{ emp.company_name }}</h6>
                            <p class="mb-1 text-body-secondary">{{ emp.description }}</p>
                        </div>
                        <div style="text-align: right;">
                            <span
                                class="badge bg-primary-subtle border border-primary-subtle text-primary-emphasis rounded-pill">{{emp.date_start}}
                                - {% if emp.date_end %}
                                {{emp.date_end}} {% else %} current {% endif %}</span>
                            <br><span class="">{{ emp.position }}</span>
                        </div>
                    </div>
                </div>

                {% endfor %}
            </div>
        </div>

        <div class="card mt-3">
            <div class="card-header">
                <i class="bi bi-code-slash"></i>
                Projects
            </div>

            <ol class="list-group list-group-flush">
                {% for prj in profile.projects.all %}

                <li class="list-group-item d-flex justify-content-between align-items-start">
                    <div class="ms-2 me-auto">
                        {% if prj.link %}
                        <a href="{{prj.link}}" class="">
                            {{ prj.name }}
                        </a>
                        {% else %}
                        <div class="fw-bold">
                            {{ prj.name }}
                        </div>
                        {% endif %}
                        <p class="text-secondary">{{ prj.description }}</p>
                    </div>
                    {% if prj.source %}
                    <a href="{{prj.source}}" class="badge bg-success-subtle border border-success-subtle text-success-emphasis rounded-pill">
                        Source
                    </a>
                    {% else %}
                    <span class="badge bg-secondary-subtle border border-secondary-subtle text-secondary-emphasis rounded-pill">
                        Private
                    </span>
                    {% endif %}
                </li>

                {% endfor %}
            </ol>

        </div>

        <div class="card mt-3">
            <div class="card-header">
                <i class="bi bi-braces"></i>
                Additionally:
            </div>
            <div class="card-body">
                {{ cv.extra_info|safe }}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %}
<script type="text/javascript">
    const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
    const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))

    document.getElementById("to-pdf-btn").addEventListener("click", function() {
        let element = document.getElementById('content');

        opt = {
            filename: 'cv.pdf',
            image: { type: 'jpeg', quality: 1 },
            enableLinks: true,
            pagebreak: {mode: ['css', 'legacy']},
            jsPDF: {
                orientation: 'p',
                unit: 'mm',
                format: 'a3',
                putOnlyUsedFonts: true,
                floatPrecision: 16,
            },
            html2canvas:  {
                dpi: 300,
                // letterRendering: true,
                width: 1150,
                height: 1920,
            },
        }

        html2pdf(element, opt);
    });
</script>
{% endblock scripts %}

src/cv/templates/cv/cv_list.html
{% extends "layout/base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block content %}

<h2 class="text-center">You're cv's</h2>

<div class="row">
  <div class="list-group col-md-6 offset-3">
    <ol class="list-group list-group-numbered mb-3">
      {% for cv in cvs %}
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <div class="ms-2 me-auto">
          <div class="mb-2">
            <a href="{% url 'cv:show' cv.pk %}" class="fw-bold">{{ cv.name }}</a>
          </div>
          <span class="badge bg-info-subtle border border-info-subtle text-info-emphasis rounded-pill">Hardskills: {{ cv.hardskills_count }}</span>
          <span class="badge bg-primary-subtle border border-primary-subtle text-primary-emphasis rounded-pill">Softskills: {{ cv.softskills_count }}</span>
        </div>
        <div>
          <a class="btn btn-primary" href="{% url 'cv:edit' cv_pk=cv.pk %}" role="button"><i class="bi bi-pencil-square"></i></a>
          <a class="btn btn-danger ml-5" href="{% url 'cv:delete' cv.pk %}" role="button"><i class="bi bi-trash"></i></a>
        </div>
      </li>
      {% endfor %}
    </ol>
  </div>
</div>


{% endblock content %}

src/cv/templates/cv/cv_manage.html
{% extends "layout/base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block style %}
<link rel="stylesheet" href="{% static 'cv/cv_manage.css' %}">
{% endblock style %}

{% block content %}

<h2 class="text-center">{% if edit %} Update cv {% else %} Create a new CV {% endif %}</h2>

<form action="{% if edit %}{% url 'cv:edit' cv_pk=cv_form.instance.id %}{% else %}{% url 'cv:create' %}{% endif %}" class="contacts_form mb-5" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="row">
        <div class="col-md-8">
            <h4>CV info:</h4>
            {{ cv_form.non_form_errors }}
            {{ cv_form.non_field_errors }}
            {{cv_form.media}}
            <div class="input-group mb-3">
                <span class="input-group-text">{{ cv_form.name.label }}</span>
                {{ cv_form.name|add_class:"form-control" }}
            </div>
            {% if cv_form.name.errors %}
                <p class="text-danger">
                    {% for error in cv_form.name.errors %}
                        {{ error }}
                    {% endfor %}
                </p>
            {% endif %}

            <div class="mb-3">
                {{ cv_form.avatar|add_class:"form-control" }}
            </div>
            {% if cv_form.avatar.errors %}
                <p class="text-danger">
                    {% for error in cv_form.avatar.errors %}
                        {{ error }}
                    {% endfor %}
                </p>
            {% endif %}

            <div class="mb-3">
                {{ cv_form.info.label_tag }}
                {{ cv_form.info|add_class:"form-control" }}
            </div>

            <div class="mb-3">
                {{ cv_form.extra_info.label_tag }}
                {{ cv_form.extra_info|add_class:"form-control"|attr:"style: height: 200px" }}
            </div>

            <button value="submit" class="btn btn-light col-md-2 col-offset-5" type="submit">Save cv</button>

        </div>

        <div class="col-md-4 skills">
            <h4>Specify skills</h4>
            {{skills_formset.management_form}}

            {{skills_formset.non_form_errors}}

            {% for form in skills_formset %}
            <div class="skill mb-3 dynamic-form-item">

                <div class="input-group mb-3">
                    <span class="input-group-text">{{ form.name.label_tag }}</span>
                    {{ form.name|add_class:"form-control" }}
                </div>
                {% if form.name.errors %}
                    <p class="text-danger">
                        {% for error in form.name.errors %}
                            {{ error }}
                        {% endfor %}
                    </p>
                {% endif %}

                <div class="input-group mb-3">
                    <span class="input-group-text">{{ form.type.label_tag }}</span>
                    {{form.type|add_class:"form-select"}}
                </div>
                {% if form.type.errors %}
                    <p class="text-danger">
                        {% for error in form.type.errors %}
                            {{ error }}
                        {% endfor %}
                    </p>
                {% endif %}

                {{ form.level.label_tag }}
                {% render_field form.level type="range" value="1" min="1" max="10" oninput="this.nextElementSibling.value = this.value" class+="form-range rng" %}
                Approximately: <output class="mb-3">{{ form.level.value }}</output>

                <div class="form-floating">
                    {{ form.description|add_class:"form-control"|attr:"style: height: 100px;" }}
                    {{ form.description.label_tag }}
                </div>
                {% if form.description.errors %}
                    <p class="text-danger">
                        {% for error in form.description.errors %}
                            {{ error }}
                        {% endfor %}
                    </p>
                {% endif %}

                {{form.id}}
                {{ form.DELETE }}

            </div>

            {% endfor %}

        </div>
    </div>

</form>

{% endblock content %}

{% block scripts %}
<script src="{% static 'js/jquery-1.3.2.min.js' %}"></script>
<script src="{% static 'js/jquery.formset.js' %}"></script>
<script type="text/javascript">
    $(function () {
        $('.skill').formset({
            prefix: '{{ skills_formset.prefix }}',
            deleteCssClass: 'link-danger delete-btn',
            keepFieldValues: '.rng'
        });
    })
</script>

{% endblock scripts %}