src/auth/urls.py
from django.urls import path

from auth.views import (
    RegisterView,
    LoginView,
    LogoutView,
    index,
)


app_name = 'auth'

urlpatterns = [
    path('', index, name='index'),

    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

src/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from core import settings


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('auth.urls', namespace='auth')),
    path('cv/', include('cv.urls', namespace='cv')),
    path('profile/', include('user.urls', namespace='user')),
]

if settings.DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls")),]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/cv/urls.py
from django.urls import path

from cv.views import (
    CvCreateView,
    CvDeleteView,
    CvEditView,
    CvItemView,
    CvListView,
)


app_name = 'cv'

urlpatterns = [
    path('list/', CvListView.as_view(), name='list'),
    path('create/', CvCreateView.as_view(), name='create'),
    path('edit/<int:cv_pk>/', CvEditView.as_view(), name='edit'),
    path('delete/<int:pk>/', CvDeleteView.as_view(), name='delete'),
    path('show/<int:pk>/', CvItemView.as_view(), name='show'),
]

src/user/urls.py
from django.urls import include, path

from user.views import (
    CourseView,
    CoursesView,
    ProfileView,
    CreateProfileView,
    EditProfileView,

    ContactView,
    EducationView,
    EmploymentView,
    ProjectsView,
)


app_name = 'user'

urlpatterns = [
    path('', ProfileView.as_view(), name='profile'),
    path('create/', CreateProfileView.as_view(), name='create_profile'),
    path('edit/', EditProfileView.as_view(), name='edit_profile'),

    path('contacts/edit/', ContactView.as_view(), name='edit_contacts'),
    path('education/edit/', EducationView.as_view(), name='edit_education'),
    path('employment/edit', EmploymentView.as_view(), name='edit_employment'),
    path('courses/edit/', CoursesView.as_view(), name='edit_courses'),
    path('projects/edit/', ProjectsView.as_view(), name='edit_projects'),

    path('courses/show/<int:course_pk>/', CourseView.as_view(), name='view_course'),

    path('language/', include('language.urls', namespace='language')),
]

src/user/forms.py
from django import forms

from user.models import (
    Contact,
    Course,
    Employment,
    Profile,
    Education,
    Project,
)


class CreateProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = [
            'first_name',
            'last_name',
            'surname',
            'date_birth',
            'birth_place',
            'residence_place',
        ]
        widgets = {
            'date_birth': forms.widgets.DateInput(attrs={'type': 'date'}),
        }


EditContactFormSet = forms.inlineformset_factory(
    Profile,
    Contact,
    fields=[
        'type',
        'data',
    ],
    can_delete=True,
    extra=1,
)


EditEducationFormSet = forms.inlineformset_factory(
    Profile,
    Education,
    can_delete=True,
    extra=1,
    fields=[
        'institution',
        'degree',
        'speciality',
        'date_start',
        'date_end',
    ],
    widgets={
        'date_start': forms.widgets.DateInput(attrs={'type': 'date'}),
        'date_end': forms.widgets.DateInput(attrs={'type': 'date'}),
    }
)


EditEmploymentFormSet = forms.inlineformset_factory(
    Profile,
    Employment,
    can_delete=True,
    extra=1,
    fields= [
        'company_name',
        'position',
        'description',
        'date_start',
        'date_end',
    ],
    widgets={
        'date_start': forms.widgets.DateInput(attrs={'type': 'date'}),
        'date_end': forms.widgets.DateInput(attrs={'type': 'date'}),
    }
)

EditCoursesFormSet = forms.inlineformset_factory(
    Profile,
    Course,
    can_delete=True,
    extra=1,
    fields= [
        'name',
        'certificate',
    ]
)

EditProjectsFormSet = forms.inlineformset_factory(
    Profile,
    Project,
    can_delete=True,
    extra=1,
    fields=[
        'name',
        'link',
        'source',
        'description',
    ]
)

src/user/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View
from django.contrib import messages
from django.contrib.auth.mixins import (
    UserPassesTestMixin
)

from user.forms import (
    CreateProfileForm,
    EditContactFormSet,
    EditCoursesFormSet,
    EditEducationFormSet,
    EditEmploymentFormSet,
    EditProjectsFormSet,
)
from user.generic import FormSetView
from user.models import Course, Profile
from user.mixins import (
    ProfileRequiredMixin,
    MyLoginRequiredMixin,
)


class ProfileView(ProfileRequiredMixin, View):    
    def get(self, request):        
        profile = Profile.prefetch_related_fields.get(user=request.user)

        context = {
            'contacts': profile.contacts.all(),
            'education_set': profile.education_set.all(),
            'languages': profile.languages.all(),
            'employments': profile.employments.all(),
            'courses': profile.courses.all(),
            'projects': profile.projects.all(),
        }

        return render(request, 'user/profile.html', context)


class EditProfileView(ProfileRequiredMixin, View):
    """view for editing existing profile"""

    def get(self, request):
        """page with update form"""
        profile_form = CreateProfileForm(instance=request.user.profile)

        return render(request, 'user/edit_profile.html', {'profile_form': profile_form})
    
    def post(self, request):
        """update form handler"""
        profile_form = CreateProfileForm(request.POST, instance=request.user.profile)

        if not profile_form.is_valid():
            messages.error(request, "Error during editing profile")
            return render(request, 'user/edit_profile.html', {'profile_form': profile_form})

        profile_form.save()

        messages.success(request, "Profile successfully edited")
        return redirect('user:profile')


class CreateProfileView(MyLoginRequiredMixin, UserPassesTestMixin, View):
    """View to create a new profile"""

    def get(self, request):
        """page with creation form"""
        profile_form = CreateProfileForm()
        return render(request, 'user/edit_profile.html', {'profile_form': profile_form})
    
    def post(self, request):
        """creation form handler"""
        profile_form = CreateProfileForm(request.POST)

        if not profile_form.is_valid():
            messages.error(request, "Error during creation profile")
            return render(request, 'user/edit_profile.html', {'profile_form': profile_form})
        
        profile = profile_form.save(commit=False)
        profile.user = request.user
        profile_form.save()

        messages.success(request, "Profile successfully created")
        return redirect('user:profile')
    
    def test_func(self):
        return not self.request.user.has_profile()


class ContactView(ProfileRequiredMixin, FormSetView):
    related_field_name = 'profile'
    FormSet = EditContactFormSet
    template_name = 'user/contacts.html'
    success_redirect = 'user:profile'


class EducationView(ProfileRequiredMixin, FormSetView):
    related_field_name = 'profile'
    FormSet = EditEducationFormSet
    template_name = 'user/education.html'
    success_redirect = 'user:profile'


class EmploymentView(ProfileRequiredMixin, FormSetView):
    related_field_name = 'profile'
    FormSet = EditEmploymentFormSet
    template_name = 'user/employment.html'
    success_redirect = 'user:profile'


class CoursesView(ProfileRequiredMixin, FormSetView):
    related_field_name = 'profile'
    FormSet = EditCoursesFormSet
    template_name = 'user/courses.html'
    success_redirect = 'user:profile'


class ProjectsView(ProfileRequiredMixin, FormSetView):
    related_field_name = 'profile'
    FormSet = EditProjectsFormSet
    template_name = 'user/projects.html'
    success_redirect = 'user:profile'


class CourseView(View):
    def get(self, request, course_pk):
        course = get_object_or_404(Course.objects.select_related('profile'), pk=course_pk)

        return render(request, 'user/course_item.html', {'course': course})

src/user/templates/user/contacts.html
{% extends "layout/base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block style %}
<link rel="stylesheet" href="{% static 'user/edit_contacts.css' %}">
{% endblock style %}

{% block content %}

<h2 style="text-align: center;">Edit contacts</h2>

<form action="{% url 'user:edit_contacts' %}" class="contacts_form mb-5" method="post">
    {% csrf_token %}
    {{form.non_field_errors}}
    {{form_set.management_form}}

    <div class="form_container" style="width: 50%;">
        {% for form in form_set %}

        <div class="contacts_group input-group mb-3">
            <span class="input-group-text">Type</span>
            {{form.type|add_class:"form-select"}}
            {{ form.type.errors }}

            {{form.data|add_class:"form-control"}}
            {{ form.data.errors }}

            {% if form.instance.pk %}
                {{form.DELETE}}
            {% endif %}

            {{form.id}}

        </div>

        {% endfor %}
        <button value="submit" class="btn btn-success col-md-2 col-offset-5" type="submit">Save data</button>
    </div>

    </div>

    {% endblock content %}

    {% block scripts %}
    <script src="{% static 'js/jquery-1.3.2.min.js' %}"></script>
    <script src="{% static 'js/jquery.formset.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            $('.contacts_group').formset({
                prefix: '{{ form_set.prefix }}',
                deleteText: 'X',
                deleteCssClass: 'input-group-text btn btn-outline-danger',
            });
        })
    </script>
    {% endblock scripts %}

src/user/templates/user/course_item.html
{% extends "layout/base.html" %}

{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'user/course.css' %}">
{% endblock style %}

{% block content %}

<h3 class="mb-4 text-center">{{ course.profile.full_name }} successfully passed course <i>{{ course.name }}</i></h3>

<img src="{{ course.certificate.url }}" class="card-img-top" alt="..." style="max-height: 75vh; object-fit: contain;">

{% endblock content %}

src/user/templates/user/courses.html
{% extends "layout/base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block style %}
<link rel="stylesheet" href="{% static 'user/edit_courses.css' %}">
{% endblock style %}

{% block content %}

<h2 style="text-align: center;">Edit courses</h2>

<form action="{% url 'user:edit_courses' %}" class="contacts_form mb-5" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.non_field_errors}}
    {{form_set.management_form}}

    <div class="form_container" style="width: 50%;">
        {% for form in form_set %}

        <div class="contacts_group dynamic-form-item mb-3">
            {{form.name.label}}
            {{form.name|add_class:"form-control mb-2"}}
            {{ form.name.errors }}

            {{form.certificate.label}}
            {{form.certificate|add_class:"form-control"}}
            {{ form.certificate.errors }}

            {% if form.instance.pk %}
            {{form.DELETE}}
            {% endif %}

            {{form.id}}

        </div>

        {% endfor %}
        <button value="submit" class="btn btn-light col-md-2 col-offset-5" type="submit">Save data</button>
    </div>

</form>

    {% endblock content %}

    {% block scripts %}
    <script src="{% static 'js/jquery-1.3.2.min.js' %}"></script>
    <script src="{% static 'js/jquery.formset.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            $('.contacts_group').formset({
                prefix: '{{ form_set.prefix }}',
                deleteCssClass: 'link-danger d-block mt-2',
            });
        })
    </script>
    {% endblock scripts %}

src/user/templates/user/create_profile.html
{% extends "layout/base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block style %}
  <link rel="stylesheet" href="{% static 'user/create_profile.css' %}">
{% endblock style %}

{% block content %}

{% if request.user.has_profile %}
  <h2 style="text-align: center;">Update profile</h2>
{% else %}
  <h2 style="text-align: center;">Create profile</h2>
{% endif %}

<div class="row profile">
  <form action="{% url 'user:create_profile' %}" method="post" class="mt-5 col-md-6 offset-md-3">
      {% csrf_token %}

      {{ profile_form.non_field_errors }}
      
      <div class="name form_part">
        <div class="name_part_set">
          <label for="last_name">Last name</label>
          {{ profile_form.last_name|add_class:"form-control name_part" }}
          <div class="invalid-feedback">{{ profile_form.last_name.errors }}</div>
        </div>
    
        <div class="name_part_set">
          <label for="first_name">First name</label>
          {{ profile_form.first_name|add_class:"form-control name_part" }}
          <div class="invalid-feedback">{{ profile_form.first_name.errors }}</div>
        </div>
    
        <div class="name_part_set">
          <label for="surname">Surname</label>
          {{ profile_form.surname|add_class:"form-control name_part" }}
          <div class="invalid-feedback">{{ profile_form.surname.errors }}</div>
        </div>
      </div>
  
      <div class="date_birth form_part">
        <label for="date_birth">Date birth</label>
        {{ profile_form.date_birth|add_class:"form-control"}}
        <div class="invalid-feedback">{{ profile_form.date_birth.errors }}</div>
      </div>
  
      <div class="form_part place">
        <div class="place_part">
          <label for="birth_place">Born place</label>
          {{ profile_form.birth_place|add_class:"form-control"}}
          <div class="invalid-feedback">{{ profile_form.birth_place.errors }}</div>
        </div>
  
        <div class="place_part">
          <label for="residence_place">Residence place</label>
          {{ profile_form.residence_place|add_class:"form-control"|append_attr:"placeholder:Leave blank if same to born place"}}
          <div class="invalid-feedback">{{ profile_form.residence_place.errors }}</div>
        </div>
      </div>
      
      <button value="submit" class="btn btn-light" type="submit">Save data</button>
    </form>

    <!-- <form action="" class="col-md-6 contact_form">
      <h4>Contacts</h4>
      <div class="contact_form_container">
        {% csrf_token %}
  
        {% for contact_form in contact_form_set %}
  
        <div class="contact_form_group mb-3">
          <div class="contact_form_item">
            <label class="form-label" for="type">Contact type</label>
            {{ contact_form.type|add_class:'form-select' }}
          </div>
    
          <div class="contact_form_item">
            <label class="form-label" for="type">Contact data</label>
            {{ contact_form.link|add_class:'form-control' }}
          </div>
        </div>
  
        {% endfor %}
      </div>
    </form> -->

</div>

{% endblock content %}

src/user/templates/user/edit_contacts.html
{% extends "layout/base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block style %}
<link rel="stylesheet" href="{% static 'user/edit_contacts.css' %}">
{% endblock style %}

{% block content %}

<h2 style="text-align: center;">Edit contacts</h2>

<form action="{% url 'user:edit_contacts' %}" class="contacts_form mb-5" method="post">
    {% csrf_token %}
    {{form.non_field_errors}}
    {{form_set.management_form}}

    <div class="form_container row">
        {% for form in form_set %}

        <div class="contacts_group col-md-4 mb-5">
            {{form.type.label}}
            {{form.type|add_class:"form-select mb-2"}}
            {{ form.type.errors }}

            {{form.link.label}}
            {{form.link|add_class:"form-control"}}
            {{ form.link.errors }}

            {{form.DELETE|add_class:"form-check-input"}}
            {{form.DELETE.label}}

            {{form.id}}

        </div>

        {% endfor %}
    </div>

    <button value="submit" class="btn btn-light col-md-2 col-offset-5" type="submit">Save data</button>
    </div>

    {% endblock content %}

src/user/templates/user/edit_profile.html
{% extends "layout/base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block style %}
  <link rel="stylesheet" href="{% static 'user/edit_profile.css' %}">
{% endblock style %}

{% block content %}

{% if request.user.has_profile %}
  <h2 style="text-align: center;">Update profile</h2>
{% else %}
  <h2 style="text-align: center;">Create profile</h2>
{% endif %}

<div class="row profile">
  {% if request.user.has_profile %}
  <form action="{% url 'user:edit_profile' %}" method="post" class="mt-5 col-md-6 offset-md-3">
  {% else %}
  <form action="{% url 'user:create_profile' %}" method="post" class="mt-5 col-md-6 offset-md-3">
  {% endif %}
      {% csrf_token %}

      {{ profile_form.non_field_errors }}
      
      <div class="name form_part">
        <div class="name_part_set">
          <label for="last_name">Last name</label>
          {{ profile_form.last_name|add_class:"form-control name_part" }}
          <div class="invalid-feedback">{{ profile_form.last_name.errors }}</div>
        </div>
    
        <div class="name_part_set">
          <label for="first_name">First name</label>
          {{ profile_form.first_name|add_class:"form-control name_part" }}
          <div class="invalid-feedback">{{ profile_form.first_name.errors }}</div>
        </div>
    
        <div class="name_part_set">
          <label for="surname">Surname</label>
          {{ profile_form.surname|add_class:"form-control name_part" }}
          <div class="invalid-feedback">{{ profile_form.surname.errors }}</div>
        </div>
      </div>
  
      <div class="date_birth form_part input-group">
        <span class="input-group-text" id="basic-addon2">{{ profile_form.date_birth.label }}</span>
        {{ profile_form.date_birth|add_class:"form-control"}}
        <div class="invalid-feedback">{{ profile_form.date_birth.errors }}</div>
      </div>
  
      <div class="form_part place">
        <div class="place_part">
          <label for="birth_place">Born place</label>
          {{ profile_form.birth_place|add_class:"form-control"}}
          <div class="invalid-feedback">{{ profile_form.birth_place.errors }}</div>
        </div>
  
        <div class="place_part">
          <label for="residence_place">Residence place</label>
          {{ profile_form.residence_place|add_class:"form-control"|append_attr:"placeholder:Leave blank if same to born place"}}
          <div class="form-text">Leave blank if matches with born place.</div>
          <div class="invalid-feedback">{{ profile_form.residence_place.errors }}</div>
        </div>
      </div>
      
      <button value="submit" class="btn btn-light" type="submit">Save data</button>
    </form>

    <!-- <form action="" class="col-md-6 contact_form">
      <h4>Contacts</h4>
      <div class="contact_form_container">
        {% csrf_token %}
  
        {% for contact_form in contact_form_set %}
  
        <div class="contact_form_group mb-3">
          <div class="contact_form_item">
            <label class="form-label" for="type">Contact type</label>
            {{ contact_form.type|add_class:'form-select' }}
          </div>
    
          <div class="contact_form_item">
            <label class="form-label" for="type">Contact data</label>
            {{ contact_form.link|add_class:'form-control' }}
          </div>
        </div>
  
        {% endfor %}
      </div>
    </form> -->

</div>

{% endblock content %}

src/user/templates/user/education.html
{% extends "layout/base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block style %}
<link rel="stylesheet" href="{% static 'user/education.css' %}">
{% endblock style %}

{% block content %}

<h2 style="text-align: center;">Edit education</h2>

<form action="{% url 'user:edit_education' %}" class="mb-5" method="post">
    {% csrf_token %}
    {{form.non_field_errors}}
    {{form_set.management_form}}

    <div class="form_container">
        {% for form in form_set %}

        <div class="edu mb-3 dynamic-form-item" style="width: 60%;">
            <!-- institution field -->
            {{ form.institution.label }}
            {{ form.institution|add_class:"form-control mb-2" }}
            {{ form.institution.errors }}

            <div class="input-group mb-2">
                <!-- degree field -->
                <span class="input-group-text">Degree</span>
                {{ form.degree|add_class:"form-control" }}
                {{ form.degree.errors }}
    
                <!-- speciality field -->
                <span class="input-group-text">Field</span>
                {{ form.speciality|add_class:"form-control" }}
                {{ form.speciality.errors }}
            </div>

            <div class="input-group">
                <!-- date_start field -->
                <span class="input-group-text">Begin</span>
                {{ form.date_start|add_class:"form-control" }}
                {{ form.date_start.errors }}
    
                <!-- date_end field -->
                <span class="input-group-text">Ended</span>
                {{ form.date_end|add_class:"form-control" }}
                {{ form.date_end.errors }}
            </div>

            {% if form.instance.pk %}
            {{form.DELETE|add_class:"form-check-input"}}
            {% endif %}


            {{form.id}}

        </div>

        {% endfor %}
        <button value="submit" class="edu_btn btn btn-light" type="submit">Save data</button>
    </div>
    </form>

    </div>

    {% endblock content %}

    {% block scripts %}
    <script src="{% static 'js/jquery-1.3.2.min.js' %}"></script>
    <script src="{% static 'js/jquery.formset.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            $('.edu').formset({
                prefix: '{{ form_set.prefix }}',
                deleteCssClass: 'link-danger d-block mt-3',
            });
        })
    </script>
    {% endblock scripts %}

src/user/templates/user/profile.html
{% extends "layout/base.html" %}

{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'user/profile.css' %}">
{% endblock style %}

{% block content %}

<div class="row1">
  <div class="prof card">
    <div class="card-header">
      <b class="header_item">Profile</b>
      <a href="{% url 'user:edit_profile' %}" class="link-secondary header_item"><i class="bi bi-pencil-square"></i></a>
    </div>
    <div class="card-body">
      <h5 class="card-title">{{ request.user.profile.full_name }}</h5>
      <p class="card-text"><b>Born date: </b>{{ request.user.profile.date_birth }}</p>
      <p class="card-text"><b>Born at: </b>{{ request.user.profile.birth_place }}</p>
      <p class="card-text"><b>Live in: </b>{{ request.user.profile.residence_place }}</p>

    </div>
  </div>
  {% if contacts %}
  <div class="contacts card">
    <div class="card-header">
      <b class="header_item">Contacts</b>
      <a href="{% url 'user:edit_contacts' %}" class="link-secondary header_item"><i class="bi bi-pencil-square"></i></a>
    </div>
    <ul class="list-group list-group-flush ">
      {% for contact in contacts %}
      <li class="list-group-item">{{ contact.template }}</li>
      {% endfor %}
    </ul>
  </div>
  {% endif %}

  {% if languages %}
  <div class="card lan">
    <div class="card-header">
      <b class="header_item">Possessing languages</b>
      <a href="{% url 'user:language:edit_languages' %}" class="link-secondary header_item"><i class="bi bi-pencil-square"></i></a>
    </div>

    <ul class="list-group list-group-flush">
      {% for lan in languages %}
      <li class="list-group-item"><b>{{ lan.name }}: </b>{{ lan.level }}</li>
      {% endfor %}
    </ul>
  </div>
  {% endif %}

</div>

<div class="row1">
  {% if education_set %}
  <div class="edu card">
    <div class="card-header">
      <b class="header_item">Education history</b>
      <a href="{% url 'user:edit_education' %}" class="link-secondary header_item"><i class="bi bi-pencil-square"></i></a>
    </div>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Institution</th>
          <th scope="col">Speciality</th>
          <th scope="col">Degree</th>
          <th scope="col">Date begin</th>
          <th scope="col">Date end</th>
        </tr>
      </thead>

      <tbody>
        {% for edu in education_set %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td>{{ edu.institution }}</td>
          <td>{{ edu.speciality }}</td>
          <td>{{ edu.degree }}</td>
          <td>{{ edu.date_start }}</td>
          {% if edu.date_end %}
          <td>{{ edu.date_end }}</td>
          {% else %}
          <td>Current</td>
          {% endif %}
        </tr>

        {% endfor %}
    </table>
  </div>
  {% endif %}

  {% if employments %}
  <div class="emp card">
    <div class="card-header">
      <b class="header_item">Employment history</b>
      <a href="{% url 'user:edit_employment' %}" class="link-secondary header_item"><i class="bi bi-pencil-square"></i></a>
    </div>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Company</th>
          <th scope="col">Position</th>
          <th scope="col">Time working</th>
          <th scope="col">Description</th>
        </tr>
      </thead>

      <tbody>
        {% for emp in employments %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td>{{ emp.company_name }}</td>
          <td>{{ emp.position }}</td>
          <td>{{ emp.date_start }} - {% if emp.date_end %} {{ emp.date_end }} {% else %}current{% endif %}</td>
          <td>{{ emp.description|truncatechars:30 }}...</td>
        </tr>

        {% endfor %}
    </table>
  </div>
  {% endif %}
</div>

<div class="row1">
  {% if projects %}
  <div class="card prj">
    <div class="card-header">
      <b class="header_item">Projects</b>
      <a href="{% url 'user:edit_projects' %}" class="link-secondary header_item"><i class="bi bi-pencil-square"></i></a>
    </div>
    <div class="card-body">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Link</th>
            <th scope="col">Source code</th>
            <th scope="col">Description</th>
          </tr>
        </thead>
        <tbody>
          {% for prj in projects %}
          <tr>
            <td>{{ prj.name }}</td>
            <td>
              {% if prj.link %}
                <a href="{{ prj.link }}">Link</a>
              {% else %}
                Not hosted
              {% endif %}
            </td>
            <td>
              {% if prj.source %}
                <a href="{{ prj.source }}">Source</a>
              {% else %}
                Private
              {% endif %}
            </td>
            <td>{{ prj.description|truncatechars:25 }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  {% endif %}

  {% if courses %}

  <div class="card crs">
    <div class="card-header">
      <b class="header_item">Passed courses</b>
      <a href="{% url 'user:edit_courses' %}" class="link-secondary header_item"><i class="bi bi-pencil-square"></i></a>
    </div>
    <div class="card-body courses row">
      {% for course in courses %}
      <div class="col-4 p-2">
        <div class="card course">
          <img src="{{ course.certificate.url }}" class="card-img-top" alt="...">
          <div class="card-body">
            <a href="{% url 'user:view_course' course.pk %}" class="card-text">{{ course.name }}</a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>

  {% endif %}

</div>

<div class="empty">
  {% if not contacts %}
  <a class="btn btn-outline-light" href="{% url 'user:edit_contacts' %}" role="button">Add contacts info</a>
  {% endif %}

  {% if not education_set %}
  <a class="btn btn-outline-light" href="{% url 'user:edit_education' %}" role="button">Add education info</a>
  {% endif %}

  {% if not employments %}
  <a class="btn btn-outline-light" href="{% url 'user:edit_employment' %}" role="button">Add employment info</a>
  {% endif %}

  {% if not languages %}
  <a class="btn btn-outline-light" href="{% url 'user:language:edit_languages' %}" role="button">Add languages info</a>
  {% endif %}

  {% if not courses %}
  <a class="btn btn-outline-light" href="{% url 'user:edit_courses' %}" role="button">Add passed courses</a>
  {% endif %}

  {% if not projects %}
  <a class="btn btn-outline-light" href="{% url 'user:edit_projects' %}" role="button">Add you're projects</a>
  {% endif %}
</div>

{% endblock content %}