src/auth/urls.py
from django.urls import path

from auth.views import (
    RegisterView,
    LoginView,
    LogoutView,
    index,
)


app_name = 'auth'

urlpatterns = [
    path('', index, name='index'),

    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

src/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from core import settings


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('auth.urls', namespace='auth')),
    path('cv/', include('cv.urls', namespace='cv')),
    path('profile/', include('user.urls', namespace='user')),
]

if settings.DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls")),]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/cv/urls.py
from django.urls import path

from cv.views import (
    CvCreateView,
    CvDeleteView,
    CvEditView,
    CvItemView,
    CvListView,
)


app_name = 'cv'

urlpatterns = [
    path('list/', CvListView.as_view(), name='list'),
    path('create/', CvCreateView.as_view(), name='create'),
    path('edit/<int:cv_pk>/', CvEditView.as_view(), name='edit'),
    path('delete/<int:pk>/', CvDeleteView.as_view(), name='delete'),
    path('show/<int:pk>/', CvItemView.as_view(), name='show'),
]

src/user/urls.py
from django.urls import include, path

from user.views import (
    CourseView,
    CoursesView,
    ProfileView,
    CreateProfileView,
    EditProfileView,

    ContactView,
    EducationView,
    EmploymentView,
    ProjectsView,
)


app_name = 'user'

urlpatterns = [
    path('', ProfileView.as_view(), name='profile'),
    path('create/', CreateProfileView.as_view(), name='create_profile'),
    path('edit/', EditProfileView.as_view(), name='edit_profile'),

    path('contacts/edit/', ContactView.as_view(), name='edit_contacts'),
    path('education/edit/', EducationView.as_view(), name='edit_education'),
    path('employment/edit', EmploymentView.as_view(), name='edit_employment'),
    path('courses/edit/', CoursesView.as_view(), name='edit_courses'),
    path('projects/edit/', ProjectsView.as_view(), name='edit_projects'),

    path('courses/show/<int:course_pk>/', CourseView.as_view(), name='view_course'),

    path('language/', include('language.urls', namespace='language')),
]

src/core/templates/include/_flash_messages.html
{%  if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

{% comment %}
{% if messages %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>$(document).ready(function () { $(".toast").toast('show'); });</script>

{% for message in messages %}
<div class="toast align-items-center border-0 text-bg-{{message.tags}}" role="alert" aria-live="assertive" aria-atomic="true">
    <div class="d-flex">
        <div class="toast-body">
            Hello, world! This is a toast message.
        </div>
        <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast"
            aria-label="Close"></button>
    </div>
</div>
{% endfor %}
{% endif %}
{% endcomment %}

src/core/templates/include/_footer.html
<footer class="footer mt-auto py-3 bg-body-tertiary">
  <p class="text-center text-muted m-0">© 2023 andrymyzik</p>
</footer>

src/core/templates/include/_navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary mb-3">
  <div class="container-fluid container">
    <a class="navbar-brand disabled" href="">CV-Simplifier</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a href="{% url 'cv:list' %}" class="nav-link"><i class="bi bi-list-task"></i> My cv's</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a href="{% url 'cv:create' %}" class="nav-link"><i class="bi bi-plus-square"></i> Create cv</a>
        </li>
      </ul>
      {% if request.user.is_superuser %}
      <div class="nav-item" style="margin-right: 15px;">
        <a class="nav-link" href="{% url 'admin:index' %}">Admin dashboard</a>
      </div>
      {% endif %}
      <div style="margin-right: 15px;" class="nav-item">
        <a href="" class="nav-link">About us</a>
      </div>
      <div class="nav-item dropdown btn btn-outline-secondary ml-3">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          {% if request.user.is_authenticated %}
          {{ request.user.username }}
          {% else %}
          Not authenticated
          {% endif %}
        </a>
        <ul class="dropdown-menu">
          {% if request.user.is_authenticated %}
          <li><a class="dropdown-item" href="{% url 'user:profile' %}">Profile <i class="bi bi-person-fill"></i></a></li>
          <li><a class="dropdown-item text-danger-emphasis" href="{% url 'auth:logout' %}">Log out <i class="bi bi-box-arrow-left"></i></a></li>
          {% else %}
          <li><a class="dropdown-item" href="{% url 'auth:login' %}">Log in</a></li>
          <li><a class="dropdown-item" href="{% url 'auth:register' %}">Register</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  </div> 
</nav>

src/core/templates/include/_save_pdf_btn.html
<style>
    #to-pdf-btn {
        width: 100px;
        position: fixed;
        left: 0;
        bottom: 0;
        margin: 30px;
        opacity: 30%;
        z-index: 99999;
    }

    #to-pdf-btn:hover {
        opacity: 80%;
    }

</style>


<button data-html2canvas-ignore id="to-pdf-btn" class="btn btn-sm btn-primary">Save as PDF</button>

src/core/templates/include/_switcher.html
<div class="form-check form-switch switcher">
    <label class="form-check-label" for="flexSwitchCheckDefault">☀</label>
    <input class="form-check-input" type="checkbox" role="switch" id="theme-switcher">
</div>